language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

matrix:
  include:
    - php: 7.4snapshot
      env: WP_VERSION=latest PHPUNIT_VERSION=7.5.17
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=lint
    - php: 7.3
      env: WP_TRAVISCI=test-js
    - php: 7.3
      env: WP_TRAVISCI=test-e2e

# Make sure NodeGit gets the correct C libs, copied from Gutenberg.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

before_install:
  - |
    if [[ "$WP_TRAVISCI" == "test-e2e" ]] ; then
      # Upgrade docker-compose, copied from Gutenberg.
      sudo rm /usr/local/bin/docker-compose
      curl -sL https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64 > docker-compose
      chmod +x docker-compose
      sudo mv docker-compose /usr/local/bin
    fi

install:
  - composer install
  - nvm install --lts
  - npm install

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ -z "$PHPUNIT_VERSION" ]] ; then
        PHPUNIT_VERSION=5.7.9
      fi

      composer global require "phpunit/phpunit=$PHPUNIT_VERSION"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "lint" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
      npm run lint:js
    fi

script:
  - npm run build
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
  - |
    if [[ "$WP_TRAVISCI" == "test-js" ]] ; then
      npm run test:js
    fi
  - |
    if [[ "$WP_TRAVISCI" == "test-e2e" ]] ; then
      npm run env start
      npm run test:e2e
    fi
